services:
  mysql:
    name: MySQL Database
    triggeredBy: ["postDevcontainerStart"]
    commands:
      start: sudo service mysql start
      ready: sudo mysql -uroot -e "SHOW DATABASES;"

tasks:
  setup:
    name: "Setup (Steps 1-5)"
    triggeredBy: ["postDevcontainerStart"]
    command: bash .devcontainer/setup.sh
