services:
  mysql:
    name: MySQL Database
    triggeredBy: ["postDevcontainerStart"]
    commands:
      start: sudo service mysql start
      ready: sudo mysql -uroot -e "SHOW DATABASES;"

tasks:
  setup:
    name: "Project Setup"
    triggeredBy: ["postDevcontainerStart"]
    command: bash .devcontainer/setup.sh
    init: true
    openMode: split-bottom

  dev:
    name: "Start Dev Servers"
    command: composer run dev
    triggeredBy: ["manual"]
    openMode: split-right
